packages:
  - apps/*
  - packages/*

catalog:
  "@libsql/client": 0.17.2
  "@types/node": 25.6.0
  "@vitest/browser-playwright": 4.1.4
  drizzle-orm: 0.45.2
  playwright: 1.58.2
  typescript: 6.0.3
  vitest: 4.1.4

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - workerd
